from pydantic import BaseModel

class response(BaseModel):
    status: str
    code:int
    message: str
    error: str | None = None
    data: dict|list| None = None

errorMessages = {
    "MISSING_FIELDS": "One or more mandatory fields are missing.",
    "INVALID_CREDENTIALS": "The provided credentials are invalid.",     
}

MESSAGES = {
    "LEAD_MISSING_FIELDS": "All mandatory fields (name, company_name, city, state, contect_1, inquery_type, email, requirement, progress) are required.",
    "LEAD_ADD_UNAUTHORIZED": "Only admin can add lead.",
    "LEAD_ADDED_SUCCESS": "lead added successfully",
    "LEAD_ADD_FAILED": "Failed to add lead",
    "INVALID_STAGE": "Invalid stage value provided. Must be 'open', 'closed', or 'in progress'.",
    "INVALID_PROGRESS": "Invalid progress value provided. Must be 'Warm', 'Hot', 'Cold', or 'PO Raised'",
    "ASSIGN_MISSING_FIELDS": "All mandatory fields (lead_id, assiged_to) are required.",
    "ASSIGN_UNAUTHORIZED": "Only admin can assign lead.",
    "LEAD_ASSIGNED_SUCCESS": "lead assigned successfully",
    "LEAD_ASSIGN_FAILED": "Failed to assign lead",
    "NO_LEADS_FOUND": "No leads found",
    "NO_LEADS_FOR_USER": "No leads found for the use",
    "LEADS_FETCHED_SUCCESS": "Leads feached successfully.",
    "LEADS_FETCH_FAILED": "Failed to fetch leads",
    "UPDATE_MISSING_FIELDS": "All mandatory fields (lead_id, name) are required.",
    "UPDATE_UNAUTHORIZED": "Only admin can update lead.",
    "NO_FIELDS_TO_UPDATE": "No fields to update",
    "LEAD_UPDATED_SUCCESS": "Lead updated successfully",
    "LEAD_UPDATE_FAILED": "Failed to fetch lead",
    "STATUS_UPDATE_UNAUTHORIZED": "Only admin and salesman can update lead status.",
    "STATUS_UPDATE_UNAUTHORIZED_ASSIGNED": "Only admin and assigned salesman can update lead status.",
    "LEAD_NOT_FOUND": "Lead not fount in the database",
    "LEAD_STATUS_UPDATED_SUCCESS": "Leads status updated  successfully.",
    "LEAD_STATUS_UPDATE_FAILED": "Failed to fetch lead detailsd",
    "LEAD_ID_REQUIRED": "Lead ID is required.",
    "LEAD_CLOSED_SUCCESS": "Leads closed successfully.",
    "LEAD_CLOSE_FAILED": "Failed to fetch lead detailsd",
    "COUNT_UNAUTHORIZED": "Only admin can get lead counts.",
    "LEAD_COUNT_SUCCESS": "lead count feched successfully.",
    "LEAD_COUNT_FAILED": "Failed to fetch lead count",
    "EXCEL_FILE_MANDATORY": "Excel file is mandatory.",
    "INVALID_FILE_FORMAT": "Invalid file format. Missing required headers.",
    "DB_CONNECTION_FAILED": "Database connection failed.",
    "FILE_IMPORT_SUCCESS": "File validated and data saved successfully!",
    "FILE_IMPORT_FAILED": "An error occurred while processing the file.",
    "CSV_TEMPLATE_FAILED": "Failed to generate CSV template.",
    # Company Admin Messages
    "LOGIN_ERROR": "There is an error in companyadmin_login.",
    "EMPLOYEE_LIST_UNAUTHORIZED": "Only admin can access employee list",
    "EMPLOYEE_LIST_SUCCESS": "Employee List feched successfully.",
    "EMPLOYEE_UPDATE_MISSING_FIELDS": "All mandatory fields (name, username, role, id) are required.",
    "EMPLOYEE_UPDATE_UNAUTHORIZED": "Only admin and hr can update employee details",
    "EMPLOYEE_UPDATED_SUCCESS": "Employee details updated Successfully.",
    "EMPLOYEE_UPDATE_FAILED": "There is some error while Updating the employee",
    "EMPLOYEE_ADD_MISSING_FIELDS": "All mandatory fields (name, username, password, role, photos) are required.",
    "EMPLOYEE_ADD_UNAUTHORIZED": "Only admin and hr can add employee",
    "EMPLOYEE_PHOTOS_REQUIRED": "Exactly 4 photos are required.",
    "EMPLOYEE_ADMIN_RESTRICTION": "Cannot add Admin. Only Edquest can add Admin users.",
    "EMPLOYEE_ADDED_SUCCESS": "Employee added Successfully.",
    "EMPLOYEE_ADD_FAILED": "There is some error while adding the employee",
    "ROLES_UNAUTHORIZED": "Only admin and HR can access roles.",
    "ROLES_SUCCESS": "Roles",
    "EMPLOYEE_ID_REQUIRED": "Employee ID is required.",
    "EMPLOYEE_DELETE_UNAUTHORIZED": "Only admin and hr can delete employee",
    "EMPLOYEE_DELETED_SUCCESS": "Employee Deleted Successfully.",
    "EMPLOYEE_DELETE_FAILED": "There is some error while Deleting the employee",
    # Attendance Messages
    "ATTENDANCE_UNAUTHORIZED": "Only admin and HR can access all employee attendence.",
    "ATTENDANCE_FETCHED_SUCCESS": "Roles",
    # Project Messages
    "PROJECT_ASSIGN_REQUIRED_FIELDS": "All mandatory fields (project_id, assiged_to) are required.",
    "PROJECT_ASSIGN_UNAUTHORIZED": "Only admin can Assign Project.",
    "PROJECT_ASSIGNED_SUCCESS": "Project assigned successfully",
    "PROJECT_ASSIGN_FAILED": "Failed to assign Project",
    "PROJECT_STATUS_REQUIRED_FIELDS": "All mandatory fields (project_id, status) are required.",
    "PROJECT_STATUS_UPDATE_UNAUTHORIZED": "Only admin and consultant can update Project status.",
    "PROJECT_NOT_FOUND": "Project not fount in the database",
    "PROJECT_STATUS_UPDATE_UNAUTHORIZED_ASSIGNED": "Only admin and assigned Consultant can update Project status.",
    "PROJECT_STATUS_UPDATED": "Project Status Updated",
    "PROJECT_STATUS_UPDATE_FAILED": "Failed to update project status",
    "PROJECT_ID_REQUIRED": "Project ID is required.",
    "PROJECT_REVIEW_UNAUTHORIZED": "Only admin and consultant can Raise Review request.",
    "PROJECT_REVIEW_UNAUTHORIZED_ASSIGNED": "Only admin and assigned Consultant can Raise Review request..",
    "PROJECT_REVIEW_RAISED_SUCCESS": "Review request raised successfully",
    "PROJECT_CLOSE_UNAUTHORIZED": "Only admin and customer can Raise Review request.",
    "PROJECT_CLOSED_SUCCESS": "Project closed successfully",
    "PROJECT_CLOSE_FAILED": "Failed to close project",
    "PROJECT_VIEW_UNAUTHORIZED": "Only admin and customer can view Projects.",
    "PROJECT_INVALID_PROGRESS": "Invalid progress value provided. Must be 'PO Raised' and 'review raised'",
    "PROJECT_FETCHED_SUCCESS": "project feached successfully.",
    "PROJECT_FETCH_FAILED": "Failed to close project",
    "PROJECT_COUNT_UNAUTHORIZED": "Only admin can get Project counts.",
    "PROJECT_COUNT_SUCCESS": "projects count feched successfully.",
    "PROJECT_COUNT_FAILED": "Failed to fetch project count",
    # Auth Messages
    "USER_DATA_FETCHED": "User data fetched.",
    "NO_USER_FOUND": "No user found.",
    "USER_FETCH_ERROR": "Error while fetching user",
    # Error Messages for Try-Except Blocks
    "ATTENDANCE_FETCH_ERROR": "Error while fetching attendance",
    "EMPLOYEE_ATTENDANCE_FETCH_ERROR": "Error while fetching employee attendance",
    "ROLES_FETCH_ERROR": "Error while fetching roles",
}
