name: Model Training Pipeline

on:
  push:
    branches:
      - yogeshbhatt

jobs:
  deploy:
    name: Build & Deploy Skybound
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.13"

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Install uv
        run: |
          curl -LsSf https://astral.sh/uv/install.sh | sh
          echo "$HOME/.cache/uv/bin" >> $GITHUB_PATH

      - name: Install dependencies
        run: |
          uv venv .venv
          source .venv/bin/activate
          uv sync

      # Step 4: Deploy Lambda Function
      - name: Run FastAPI Application
        run: uv run uvicorn skybound_backend.main:app --host 0.0.0.0 --port 8000

      - name: Notify success
        run: echo "AWS Lambda Function deployed successfully!"
