name: Model Training Pipeline

on:
  push:
    branches:
      - revamp-be

jobs:
  deploy:
    name: Build & Deploy Skybound
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Add SSH key
        uses: webfactory/ssh-agent@v0.5.4
        with:
          ssh-private-key: ${{ secrets.EC2_KEY }}

      - name: Deploy to EC2
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << 'EOF'
            cd ~/skybound-backend

            # Pull latest code on correct branch
            if [ -d ".git" ]; then
                echo "Resetting repository to match remote..."
                git fetch origin
                git checkout revamp-be
                git reset --hard origin/revamp-be
                git clean -fd
            else
                git clone -b revamp-be https://github.com/edquestofficial/skybound-backend.git .
            fi

            curl -LsSf https://astral.sh/uv/install.sh | sh
            echo "$HOME/.cache/uv/bin" >> $GITHUB_PATH

            # Create venv if not exists
            uv venv .venv
            source .venv/bin/activate
            uv sync

            # Restart backend
            sudo systemctl restart fastapi
          EOF

      - name: Notify success
        run: echo "AWS Lambda Function deployed successfully!"
